#liste?
#sözlük?


kisaltmalarsozlugu = {
    "prof": "profesör",
    "gg": "good game",
    "dr": "doktor",
    "ok": "tamam",
    "asap": "en kısa zamanda",
    "brb": "birazdan döneceğim",
    "idk": "bilmiyorum",
    "omg": "aman tanrım",
    "tbh": "dürüst olmak gerekirse",
    "fyi": "bilgin olsun",
    "btw": "bu arada",
    "afaik": "bildiğim kadarıyla",
    "imo": "bence",
    "irl": "gerçek hayatta",
    "jk": "şaka yapıyorum",
    "np": "sorun değil",
    "rn": "şu anda",
    "smh": "başımı sallıyorum",
    "thx": "teşekkürler",
    "u": "sen",
    "ur": "senin",
    "msg": "mesaj",
    "pls": "lütfen",
    "bff": "en iyi arkadaş",
    "dm": "özel mesaj",
    "aka": "diğer adıyla",
    "wfh": "evden çalışma",
    "otp": "tek kullanımlık parola",
    "eta": "tahmini varış zamanı",
    "nvm": "boşver",
    "atm": "şu anda",
    "bc": "çünkü",
    "cya": "görüşürüz",
    "faq": "sıkça sorulan sorular",
    "bio": "biyografi",
    "cv": "özgeçmiş",
    "dept": "departman",
    "est": "kurulmuş",
    "etc": "ve benzeri",
    "gov": "hükümet",
    "inc": "şirket",
    "info": "bilgi",
    "lab": "laboratuvar",
    "min": "dakika",
    "max": "maksimum",
    "temp": "sıcaklık",
    "vol": "hacim",
    "vs": "karşı",
    "aka": "nam-ı diğer",
    "vip": "çok önemli kişi",
    "tbt": "geçmişe dönüş",
    "nsfw": "işe uygun olmayan",
    "lol": "yüksek sesle gülmek",
    "lmao": "çok gülüyorum",
    "wtf": "ne oluyor böyle",
    "wyd": "ne yapıyorsun",
    "imo": "bence",
    "idc": "umrumda değil",
    "irl": "gerçek hayatta",
    "aka": "namı diğer",
    "gr8": "harika",
    "cu": "görüşürüz",
    "bday": "doğum günü",
    "bf": "erkek arkadaş",
    "gf": "kız arkadaş",
    "tba": "daha sonra duyurulacak",
    "tbd": "belirlenecek",
    "dept": "bölüm",
    "ref": "hakem",
    "asst": "yardımcı",
    "appt": "randevu",
    "exp": "deneyim",
    "hr": "insan kaynakları",
    "mgr": "yönetici",
    "rep": "temsilci",
    "addr": "adres",
    "bldg": "bina",
    "apt": "daire",
    "no.": "numara",
    "intl": "uluslararası",
    "edu": "eğitim",
    "sci": "bilim",
    "eng": "mühendislik",
    "math": "matematik",
    "phy": "fizik",
    "chem": "kimya",
    "bio": "biyoloji",
    "hist": "tarih",
    "geo": "coğrafya",
    "comp": "bilgisayar",
    "lit": "edebiyat",
    "lang": "dil",
    "econ": "ekonomi",
    "soc": "sosyoloji",
    "pol": "siyaset",
    "psy": "psikoloji",
    "med": "tıp",
    "phd": "doktora",
    "mba": "işletme yüksek lisansı",
    "bsc": "lisans diploması",
    "msc": "yüksek lisans",
    "ba": "lisans",
    "ma": "yüksek lisans"
}



for i in range(5):
    word=input("sormak istediğiniz kelimeyi yazınız")
    if word in kisaltmalarsozlugu.keys():
        print(kisaltmalarsozlugu[word])
